import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  bool _isEnglish = false;

  bool get isEnglish => _isEnglish;

  void toggleLanguage() {
    _isEnglish = !_isEnglish;
    notifyListeners();
  }

  String translate(String key, {Map<String, String>? params}) {
    String text = _isEnglish ? _englishTranslations[key] ?? key : _germanTranslations[key] ?? key;
    if (params != null) {
      params.forEach((key, value) {
        text = text.replaceAll('{$key}', value);
      });
    }
    return text;
  }

  static final Map<String, String> _germanTranslations = {
    'search': 'Suchen...',
    'popular_categories': 'Beliebte Kategorien',
    'recommended': 'Empfohlen für dich',
    'search_results': 'Suchergebnisse',
    'no_products_found': 'Keine Produkte gefunden',
    'add_to_cart': 'In den Warenkorb',
    'added_to_cart': 'wurde zum Warenkorb hinzugefügt',
    'go_to_cart': 'Zum Warenkorb',
    'add_to_favorites': 'Zu Favoriten hinzufügen',
    'remove_from_favorites': 'Aus Favoriten entfernen',
    'add_to_list': 'Zu Liste hinzufügen',
    'remove_from_lists': 'Aus Listen entfernen',
    'close': 'Schließen',
    'product_in_no_list': 'Dieses Produkt ist in keiner Liste',
    'my_favorites': 'Meine Favoriten',
    'all_lists': 'Alle Listen',
    'manage_lists': 'Listen verwalten',
    'no_products_in_list': 'Keine Produkte in dieser Liste',
    'create_list': 'Neue Liste erstellen',
    'list_name': 'Listenname',
    'cancel': 'Abbrechen',
    'create': 'Erstellen',
    'rename_list': 'Liste umbenennen',
    'new_name': 'Neuer Name',
    'rename': 'Umbenennen',
    'delete_list': 'Liste löschen',
    'delete_list_confirmation': 'Möchten Sie die Liste "{listName}" wirklich löschen?',
    'delete': 'Löschen',
    'description': 'Beschreibung',
    'seller': 'Verkäufer',
    'seller_since': 'Seit {years} auf unserer Plattform',
    'products': 'Produkte',
    'login': 'Anmelden',
    'register': 'Registrieren',
    'email': 'E-Mail',
    'password': 'Passwort',
    'forgot_password': 'Passwort vergessen?',
    'no_account': 'Noch kein Konto?',
    'create_account': 'Konto erstellen',
    'already_account': 'Bereits ein Konto?',
    'login_here': 'Hier anmelden',
    'cart': 'Warenkorb',
    'cart_empty': 'Ihr Warenkorb ist leer',
    'total': 'Gesamt',
    'checkout': 'Zur Kasse',
    'continue_shopping': 'Weiter einkaufen',
    'remove_from_cart': 'Aus Warenkorb entfernen',
    'quantity': 'Menge',
    'price': 'Preis',
    'product': 'Produkt',
    'subtotal': 'Zwischensumme',
    'shipping': 'Versand',
    'tax': 'Steuern',
    'order_summary': 'Bestellübersicht',
    'payment_method': 'Zahlungsmethode',
    'shipping_address': 'Lieferadresse',
    'billing_address': 'Rechnungsadresse',
    'confirm_order': 'Bestellung bestätigen',
    'order_confirmed': 'Bestellung bestätigt',
    'thank_you': 'Vielen Dank für Ihre Bestellung!',
    'order_number': 'Bestellnummer',
    'estimated_delivery': 'Geschätzte Lieferung',
    'track_order': 'Bestellung verfolgen',
    'categories': 'Kategorien',
    'all_products': 'Alle Produkte',
    'sort_by': 'Sortieren nach',
    'filter': 'Filter',
    'price_range': 'Preisspanne',
    'rating': 'Bewertung',
    'availability': 'Verfügbarkeit',
    'in_stock': 'Auf Lager',
    'out_of_stock': 'Nicht verfügbar',
    'add_to_wishlist': 'Zur Wunschliste hinzufügen',
    'remove_from_wishlist': 'Von Wunschliste entfernen',
    'share': 'Teilen',
    'report': 'Melden',
    'related_products': 'Ähnliche Produkte',
    'customer_reviews': 'Kundenbewertungen',
    'write_review': 'Bewertung schreiben',
    'your_rating': 'Ihre Bewertung',
    'your_review': 'Ihr Kommentar',
    'submit': 'Absenden',
    'save': 'Speichern',
    'edit': 'Bearbeiten',
    'back': 'Zurück',
    'next': 'Weiter',
    'finish': 'Fertig',
    'loading': 'Laden...',
    'error': 'Fehler',
    'success': 'Erfolg',
    'warning': 'Warnung',
    'info': 'Information',
    'help': 'Hilfe',
    'settings': 'Einstellungen',
    'profile': 'Profil',
    'logout': 'Abmelden',
    'language': 'Sprache',
    'theme': 'Design',
    'notifications': 'Benachrichtigungen',
    'privacy': 'Datenschutz',
    'terms': 'Nutzungsbedingungen',
    'about': 'Über uns',
    'contact': 'Kontakt',
    'support': 'Support',
    'faq': 'FAQ',
    'search_placeholder': 'Suchen Sie nach Produkten...',
    'no_results': 'Keine Ergebnisse gefunden',
    'try_again': 'Versuchen Sie es erneut',
    'clear_filters': 'Filter zurücksetzen',
    'apply_filters': 'Filter anwenden',
    'show_more': 'Mehr anzeigen',
    'show_less': 'Weniger anzeigen',
    'all': 'Alle',
    'new': 'Neu',
    'sale': 'Angebot',
    'bestseller': 'Bestseller',
    'featured': 'Hervorgehoben',
    'trending': 'Trending',
    'popular': 'Beliebt',
    'recent': 'Kürzlich',
    'upcoming': 'Demnächst',
    'expired': 'Abgelaufen',
    'active': 'Aktiv',
    'inactive': 'Inaktiv',
    'pending': 'Ausstehend',
    'completed': 'Abgeschlossen',
    'cancelled': 'Storniert',
    'refunded': 'Erstattet',
    'processing': 'In Bearbeitung',
    'shipped': 'Versendet',
    'delivered': 'Geliefert',
    'returned': 'Zurückgesendet',
    'exchanged': 'Umtauschen',
    'gift_wrap': 'Geschenkverpackung',
    'gift_message': 'Geschenknachricht',
    'gift_card': 'Geschenkkarte',
    'coupon': 'Gutschein',
    'discount': 'Rabatt',
    'free_shipping': 'Kostenloser Versand',
    'express_shipping': 'Express-Versand',
    'standard_shipping': 'Standard-Versand',
    'pickup': 'Abholung',
    'delivery': 'Lieferung',
    'payment': 'Zahlung',
    'cash': 'Bar',
    'credit_card': 'Kreditkarte',
    'debit_card': 'Debitkarte',
    'paypal': 'PayPal',
    'bank_transfer': 'Banküberweisung',
    'invoice': 'Rechnung',
    'receipt': 'Quittung',
    'order': 'Bestellung',
    'orders': 'Bestellungen',
    'wishlist': 'Wunschliste',
    'wishlists': 'Wunschlisten',
    'favorites': 'Favoriten',
    'favorite_lists': 'Favoritenlisten',
    'cart_items': 'Warenkorbartikel',
    'cart_total': 'Warenkorb gesamt',
    'checkout_total': 'Kasse gesamt',
    'order_total': 'Bestellung gesamt',
    'shipping_total': 'Versand gesamt',
    'tax_total': 'Steuern gesamt',
    'discount_total': 'Rabatt gesamt',
    'grand_total': 'Gesamtsumme',
    'schmuck': 'Schmuck',
    'kleidung': 'Kleidung',
    'wohnen': 'Wohnen',
    'kunst': 'Kunst',
    'geschenke': 'Geschenke',
    'hochzeit': 'Hochzeit',
    'spielzeug': 'Spielzeug',
    'clear_cart': 'Warenkorb leeren',
    'clear_cart_confirmation': 'Möchten Sie den Warenkorb wirklich leeren?',
    'clear': 'Leeren',
    'order_successful': 'Bestellung erfolgreich',
    'order_successful_message': 'Vielen Dank für Ihre Bestellung!',
    'payment_method_label': 'Zahlungsmethode:',
    'email_confirmation': 'Sie erhalten in Kürze eine Bestätigung per E-Mail.',
    'ok': 'OK',
    'checkout_title': 'Zur Kasse',
    'order_summary_title': 'Bestellübersicht',
    'total_label': 'Gesamt',
    'quantity_label': 'Menge',
    'price_label': 'Preis',
    'product_label': 'Produkt',
    'subtotal_label': 'Zwischensumme',
    'shipping_label': 'Versand',
    'tax_label': 'Steuern',
    'payment_method_title': 'Zahlungsmethode',
    'shipping_address_title': 'Lieferadresse',
    'billing_address_title': 'Rechnungsadresse',
    'confirm_order': 'Bestellung bestätigen',
    'order_confirmed': 'Bestellung bestätigt',
    'thank_you': 'Vielen Dank für Ihre Bestellung!',
    'order_number': 'Bestellnummer',
    'estimated_delivery': 'Geschätzte Lieferung',
    'track_order': 'Bestellung verfolgen',
    'select_payment_method': 'Bitte wählen Sie eine Zahlungsmethode aus',
    'name': 'Name',
    'name_required': 'Bitte geben Sie Ihren Namen ein',
    'email_required': 'Bitte geben Sie Ihre E-Mail-Adresse ein',
    'email_invalid': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
    'address': 'Adresse',
    'address_required': 'Bitte geben Sie Ihre Adresse ein',
    'city': 'Stadt',
    'city_required': 'Bitte geben Sie Ihre Stadt ein',
    'zip': 'PLZ',
    'zip_required': 'Bitte geben Sie Ihre PLZ ein',
    'visa': 'Visa',
    'mastercard': 'Mastercard',
    'paypal': 'PayPal',
    'complete_order': 'Bestellung abschließen',
  };

  static final Map<String, String> _englishTranslations = {
    'search': 'Search...',
    'popular_categories': 'Popular Categories',
    'recommended': 'Recommended for you',
    'search_results': 'Search Results',
    'no_products_found': 'No products found',
    'add_to_cart': 'Add to Cart',
    'added_to_cart': 'has been added to cart',
    'go_to_cart': 'Go to Cart',
    'add_to_favorites': 'Add to Favorites',
    'remove_from_favorites': 'Remove from Favorites',
    'add_to_list': 'Add to List',
    'remove_from_lists': 'Remove from Lists',
    'close': 'Close',
    'product_in_no_list': 'This product is not in any list',
    'my_favorites': 'My Favorites',
    'all_lists': 'All Lists',
    'manage_lists': 'Manage Lists',
    'no_products_in_list': 'No products in this list',
    'create_list': 'Create New List',
    'list_name': 'List Name',
    'cancel': 'Cancel',
    'create': 'Create',
    'rename_list': 'Rename List',
    'new_name': 'New Name',
    'rename': 'Rename',
    'delete_list': 'Delete List',
    'delete_list_confirmation': 'Do you really want to delete the list "{listName}"?',
    'delete': 'Delete',
    'description': 'Description',
    'seller': 'Seller',
    'seller_since': 'On our platform since {years}',
    'products': 'Products',
    'login': 'Login',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'forgot_password': 'Forgot Password?',
    'no_account': 'Don\'t have an account?',
    'create_account': 'Create Account',
    'already_account': 'Already have an account?',
    'login_here': 'Login here',
    'cart': 'Cart',
    'cart_empty': 'Your cart is empty',
    'total': 'Total',
    'checkout': 'Checkout',
    'continue_shopping': 'Continue Shopping',
    'remove_from_cart': 'Remove from Cart',
    'quantity': 'Quantity',
    'price': 'Price',
    'product': 'Product',
    'subtotal': 'Subtotal',
    'shipping': 'Shipping',
    'tax': 'Tax',
    'order_summary': 'Order Summary',
    'payment_method': 'Payment Method',
    'shipping_address': 'Shipping Address',
    'billing_address': 'Billing Address',
    'confirm_order': 'Confirm Order',
    'order_confirmed': 'Order Confirmed',
    'thank_you': 'Thank you for your order!',
    'order_number': 'Order Number',
    'estimated_delivery': 'Estimated Delivery',
    'track_order': 'Track Order',
    'categories': 'Categories',
    'all_products': 'All Products',
    'sort_by': 'Sort by',
    'filter': 'Filter',
    'price_range': 'Price Range',
    'rating': 'Rating',
    'availability': 'Availability',
    'in_stock': 'In Stock',
    'out_of_stock': 'Out of Stock',
    'add_to_wishlist': 'Add to Wishlist',
    'remove_from_wishlist': 'Remove from Wishlist',
    'share': 'Share',
    'report': 'Report',
    'related_products': 'Related Products',
    'customer_reviews': 'Customer Reviews',
    'write_review': 'Write a Review',
    'your_rating': 'Your Rating',
    'your_review': 'Your Review',
    'submit': 'Submit',
    'save': 'Save',
    'edit': 'Edit',
    'back': 'Back',
    'next': 'Next',
    'finish': 'Finish',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Information',
    'help': 'Help',
    'settings': 'Settings',
    'profile': 'Profile',
    'logout': 'Logout',
    'language': 'Language',
    'theme': 'Theme',
    'notifications': 'Notifications',
    'privacy': 'Privacy',
    'terms': 'Terms',
    'about': 'About',
    'contact': 'Contact',
    'support': 'Support',
    'faq': 'FAQ',
    'search_placeholder': 'Search for products...',
    'no_results': 'No results found',
    'try_again': 'Try again',
    'clear_filters': 'Clear filters',
    'apply_filters': 'Apply filters',
    'show_more': 'Show more',
    'show_less': 'Show less',
    'all': 'All',
    'new': 'New',
    'sale': 'Sale',
    'bestseller': 'Bestseller',
    'featured': 'Featured',
    'trending': 'Trending',
    'popular': 'Popular',
    'recent': 'Recent',
    'upcoming': 'Upcoming',
    'expired': 'Expired',
    'active': 'Active',
    'inactive': 'Inactive',
    'pending': 'Pending',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'refunded': 'Refunded',
    'processing': 'Processing',
    'shipped': 'Shipped',
    'delivered': 'Delivered',
    'returned': 'Returned',
    'exchanged': 'Exchanged',
    'gift_wrap': 'Gift Wrap',
    'gift_message': 'Gift Message',
    'gift_card': 'Gift Card',
    'coupon': 'Coupon',
    'discount': 'Discount',
    'free_shipping': 'Free Shipping',
    'express_shipping': 'Express Shipping',
    'standard_shipping': 'Standard Shipping',
    'pickup': 'Pickup',
    'delivery': 'Delivery',
    'payment': 'Payment',
    'cash': 'Cash',
    'credit_card': 'Credit Card',
    'debit_card': 'Debit Card',
    'paypal': 'PayPal',
    'bank_transfer': 'Bank Transfer',
    'invoice': 'Invoice',
    'receipt': 'Receipt',
    'order': 'Order',
    'orders': 'Orders',
    'wishlist': 'Wishlist',
    'wishlists': 'Wishlists',
    'favorites': 'Favorites',
    'favorite_lists': 'Favorite Lists',
    'cart_items': 'Cart Items',
    'cart_total': 'Cart Total',
    'checkout_total': 'Checkout Total',
    'order_total': 'Order Total',
    'shipping_total': 'Shipping Total',
    'tax_total': 'Tax Total',
    'discount_total': 'Discount Total',
    'grand_total': 'Grand Total',
    'schmuck': 'Jewelry',
    'kleidung': 'Clothing',
    'wohnen': 'Home',
    'kunst': 'Art',
    'geschenke': 'Gifts',
    'hochzeit': 'Wedding',
    'spielzeug': 'Toys',
    'clear_cart': 'Clear Cart',
    'clear_cart_confirmation': 'Do you really want to clear the cart?',
    'clear': 'Clear',
    'order_successful': 'Order Successful',
    'order_successful_message': 'Thank you for your order!',
    'payment_method_label': 'Payment Method:',
    'email_confirmation': 'You will receive a confirmation email shortly.',
    'ok': 'OK',
    'checkout_title': 'Checkout',
    'order_summary_title': 'Order Summary',
    'total_label': 'Total',
    'quantity_label': 'Quantity',
    'price_label': 'Price',
    'product_label': 'Product',
    'subtotal_label': 'Subtotal',
    'shipping_label': 'Shipping',
    'tax_label': 'Tax',
    'payment_method_title': 'Payment Method',
    'shipping_address_title': 'Shipping Address',
    'billing_address_title': 'Billing Address',
    'confirm_order': 'Confirm Order',
    'order_confirmed': 'Order Confirmed',
    'thank_you': 'Thank you for your order!',
    'order_number': 'Order Number',
    'estimated_delivery': 'Estimated Delivery',
    'track_order': 'Track Order',
    'select_payment_method': 'Please select a payment method',
    'name': 'Name',
    'name_required': 'Please enter your name',
    'email_required': 'Please enter your email address',
    'email_invalid': 'Please enter a valid email address',
    'address': 'Address',
    'address_required': 'Please enter your address',
    'city': 'City',
    'city_required': 'Please enter your city',
    'zip': 'ZIP',
    'zip_required': 'Please enter your ZIP code',
    'visa': 'Visa',
    'mastercard': 'Mastercard',
    'paypal': 'PayPal',
    'complete_order': 'Complete Order',
  };
} 